server:
  port: 8762

spring:
  application:
    name: cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.160.85.56:5335/hotel_dc?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&zeroDateTimeBehavior=convertToNull
    username: dc_w
    password: Nj3Wn2Ed6Ak0
  aop:
    proxy-target-class=true:eureka: true
    auto: true
  redis:
    database: 0
    host: 10.160.86.233
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mybatis/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/


